import { StrictMode, useEffect, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import "./style.css";
type Session = { user: { displayName: string }; token: { accessToken: string; refreshToken: string } };
type Message = { role: "user" | "assistant"; content: string };
type SessionSummary = { sessionId: string; title: string; preview: string; messageCount: number };
const API = import.meta.env.VITE_API_BASE_URL ?? "";
const KEY = "agent-web-session";
async function request<T>(path: string, body: unknown, token?: string): Promise<T> { const r = await fetch(`${API}${path}`, { method: "POST", headers: { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) }, body: JSON.stringify(body) }); if (!r.ok) { const text = await r.text(); throw new Error(text || `请求失败（${r.status}）`); } if (r.status === 204) return undefined as T; return r.json(); }
async function getRequest<T>(path: string, token: string): Promise<T> { const r = await fetch(`${API}${path}`, { headers: { Authorization: `Bearer ${token}` } }); if (!r.ok) { const text = await r.text(); throw new Error(text || `请求失败（${r.status}）`); } return r.json(); }
function App() {
  const [session, setSession] = useState<Session | null>(() => { try { return JSON.parse(localStorage.getItem(KEY) ?? "null"); } catch { return null; } });
  const [mode, setMode] = useState<"login" | "register">("login"); const [phone, setPhone] = useState(""); const [email, setEmail] = useState(""); const [code, setCode] = useState(""); const [cooldown, setCooldown] = useState(0); const [tip, setTip] = useState(""); const [input, setInput] = useState(""); const [messages, setMessages] = useState<Message[]>([]); const [sessions, setSessions] = useState<SessionSummary[]>([]); const [sessionId, setSessionId] = useState<string | null>(null); const [sending, setSending] = useState(false); const sendingRef = useRef(false);
  useEffect(() => { if (!cooldown) return; const timer = window.setInterval(() => setCooldown(v => Math.max(0, v - 1)), 1000); return () => window.clearInterval(timer); }, [cooldown]);
  useEffect(() => { if (!session) return; void getRequest<SessionSummary[]>("/api/agent/sessions", session.token.accessToken).then(setSessions).catch(e => setTip(e instanceof Error ? e.message : "历史会话加载失败")); }, [session]);
  const sendCode = async () => { if (cooldown > 0) return; try { await request("/api/auth/email/send-code", { email }); setCooldown(60); setTip("验证码已发送，请查收邮箱"); } catch (e) { setTip(e instanceof Error ? e.message : "验证码发送失败"); } };
  const auth = async () => { if (mode === "register" && !/^1[3-9]\d{9}$/.test(phone)) { setTip("请输入正确的手机号"); return; } try { const next = await request<Session>(`/api/auth/email/${mode}`, { email, phone: mode === "register" ? phone : undefined, code }); localStorage.setItem(KEY, JSON.stringify(next)); setTip(""); setSession(next); } catch (e) { setTip(e instanceof Error ? e.message : "登录失败"); } };
  const chat = async () => { const message = input.trim(); if (!session || !message || sendingRef.current) return; sendingRef.current = true; setSending(true); setTip(""); setMessages(current => [...current, { role: "user", content: message }]); setInput(""); try { const result = await request<{ sessionId: string; reply: string }>("/api/agent/chat", { message, sessionId }, session.token.accessToken); setSessionId(result.sessionId); setMessages(current => [...current, { role: "assistant", content: result.reply }]); const latest = await getRequest<SessionSummary[]>("/api/agent/sessions", session.token.accessToken); setSessions(latest); } catch (e) { setTip(e instanceof Error ? e.message : "发送失败"); } finally { sendingRef.current = false; setSending(false); } };
  const selectSession = async (id: string) => { if (!session || sending) return; try { const detail = await getRequest<{ sessionId: string; messages: Message[] }>(`/api/agent/sessions/${encodeURIComponent(id)}`, session.token.accessToken); setSessionId(detail.sessionId); setMessages(detail.messages ?? []); setTip(""); } catch (e) { setTip(e instanceof Error ? e.message : "会话加载失败"); } };
  const newSession = () => { if (sending) return; setSessionId(null); setMessages([]); setTip(""); };
  if (!session) return <main className="auth-page"><section className="auth-brand"><img src="/travel-agent-icon.png" alt="行迹" /><div className="brand-label">行迹 · TRAVEL AI</div><h1>把下一站，<span>交给懂你的 AI</span></h1><p>从灵感到行程，从预算到攻略，为你轻松安排每一次出发。</p></section><section className="login"><div className="eyebrow">{mode === "login" ? "欢迎回来" : "创建账号"}</div><h2>{mode === "login" ? "登录行迹" : "注册行迹"}</h2>{mode === "register" && <input required placeholder="手机号" value={phone} onChange={e => setPhone(e.target.value)} />}<input type="email" required placeholder="邮箱地址" value={email} onChange={e => setEmail(e.target.value)} /><div className="code-row"><input required placeholder="邮箱验证码" value={code} onChange={e => setCode(e.target.value)} /><button type="button" disabled={cooldown > 0} onClick={() => void sendCode()}>{cooldown ? `${cooldown}s` : "获取验证码"}</button></div><button className="primary" onClick={() => void auth()}>{mode === "login" ? "登录" : "注册并登录"}</button><button className="switch" onClick={() => setMode(mode === "login" ? "register" : "login")}>{mode === "login" ? "还没有账号？立即注册" : "已有账号？返回登录"}</button>{tip && <small>{tip}</small>}</section></main>;
  return <main className="chat"><aside className="history"><button className="new-chat" type="button" onClick={newSession}>＋ 新建对话</button><div className="history-title">历史对话</div><div className="history-list">{sessions.map(item => <button type="button" key={item.sessionId} className={`history-item ${sessionId === item.sessionId ? "active" : ""}`} onClick={() => void selectSession(item.sessionId)}><strong>{item.title || "新对话"}</strong><span>{item.preview || "暂无消息"}</span></button>)}</div></aside><section className="chat-main"><header><div className="chat-brand"><img src="/travel-agent-icon.png" alt="行迹" /><div><b>行迹 · TRAVEL AI</b><h1>你的旅行助手</h1></div></div><button className="logout" onClick={() => { localStorage.removeItem(KEY); setTip(""); setMessages([]); setSessions([]); setSession(null); }}>退出登录</button></header><section className="conversation">{messages.length ? messages.map((message, index) => <div key={`${message.role}-${index}`} className={`message ${message.role}`}><div className="message-label">{message.role === "user" ? "你" : "行迹"}</div><div className="bubble">{message.content}</div></div>) : <div className="welcome"><h2>你好，我是行迹</h2><p>告诉我你想去哪里、什么时候出发，我来帮你规划旅程。</p></div>}{sending && <div className="message assistant thinking"><div className="message-label">行迹</div><div className="bubble">正在思考...</div></div>}</section><footer><input value={input} onChange={e => setInput(e.target.value)} placeholder="输入你的旅行需求..." onKeyDown={e => e.key === "Enter" && void chat()} /><button type="button" disabled={sending || !input.trim()} onClick={() => void chat()}>发送</button></footer>{tip && <div className="chat-tip">{tip}</div>}</section></main>;
}
createRoot(document.getElementById("root")!).render(<StrictMode><App /></StrictMode>);
